
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[449] =
    {   0,
      106,  104,  105,  103,  104,  105,  100,  105,  100,  104,
      105,  104,  105,  104,  105,  101,  104,  105,   56,  104,
      105,   60,  104,  105,  104,  105,   71,  104,  105,   72,
      104,  105,   53,  104,  105,   51,  104,  105,   77,  104,
      105,   52,  104,  105,   79,  104,  105,   54,  104,  105,
        1,  104,  105,    1,  104,  105,   78,  104,  105,   80,
      104,  105,   65,  104,  105,   82,  104,  105,   66,  104,
      105,   81,  104,  105,  102,  104,  105,  102,  104,  105,
      102,  104,  105,  102,  104,  105,  102,  104,  105,  102,
      104,  105,   73,  104,  105,  104,  105,   74,  104,  105,

       62,  104,  105,  102,  104,  105,  102,  104,  105,  102,
      104,  105,  102,  104,  105,  102,  104,  105,  102,  104,
      105,  102,  104,  105,  102,  104,  105,  102,  104,  105,
      102,  104,  105,  102,  104,  105,  102,  104,  105,  102,
      104,  105,  102,  104,  105,  102,  104,  105,  102,  104,
      105,  102,  104,  105,  102,  104,  105,  102,  104,  105,
       75,  104,  105,   61,  104,  105,   76,  104,  105,   63,
      104,  105,  104,  105,  104,  105,  102,  104,  105,  102,
      104,  105,  102,  104,  105,  102,  104,  105,    4,    5,
      105,    4,  105,    3,    5,  105,    3,    4,    5,  105,

        4,    5,  105,    4,    5,  105,  103,   70,    9,  101,
       89,   91,    9,   57,   86,   84,   85,   83,    2,   55,
       87,    2,    1,   64,   58,   67,   69,   68,   59,   90,
      102,  102,  102,  102,  102,    6,   93,  102,  102,   14,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,   30,  102,  102,   32,  102,   33,
      102,  102,  102,  102,  102,   50,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,   92,    9,    9,  102,
      102,    4,    4,    3,    3,    4,    4,    9,   10,   96,
       88,    1,    1,    1,    2,   95,   94,    8,    8,  102,

      102,  102,  102,   48,  102,  102,  102,  102,  102,  102,
      102,  102,   21,  102,   22,  102,  102,  102,  102,  102,
      102,   27,  102,  102,  102,  102,   43,  102,  102,  102,
      102,  102,   49,  102,  102,  102,  102,  102,   45,  102,
       39,  102,  102,  102,  102,    8,    8,    8,  102,   12,
      102,   13,  102,  102,  102,  102,  102,   46,  102,  102,
      102,  102,   23,  102,   24,  102,  102,  102,  102,   28,
      102,  102,  102,  102,   47,  102,   99,  102,  102,   36,
      102,  102,  102,   97,  102,  102,   41,  102,  102,   11,
      102,  102,  102,   16,  102,   17,  102,   18,  102,   19,

      102,  102,  102,  102,   44,  102,  102,  102,  102,  102,
       37,  102,  102,   40,  102,   42,  102,  102,   15,  102,
      102,   25,  102,  102,   29,  102,   31,  102,   34,  102,
      102,   38,  102,    7,    9,  102,  102,   26,  102,  102,
        7,    8,   98,  102,   20,  102,   35,  102
    } ;

static const flex_int16_t yy_accept[330] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        4,    7,    9,   12,   14,   16,   19,   22,   25,   27,
       30,   33,   36,   39,   42,   45,   48,   51,   54,   57,
       60,   63,   66,   69,   72,   75,   78,   81,   84,   87,
       90,   93,   96,   98,  101,  104,  107,  110,  113,  116,
      119,  122,  125,  128,  131,  134,  137,  140,  143,  146,
      149,  152,  155,  158,  161,  164,  167,  170,  173,  175,
      177,  180,  183,  186,  189,  192,  194,  197,  201,  204,
      207,  208,  209,  209,  210,  210,  211,  212,  213,  213,
      214,  214,  215,  216,  217,  218,  219,  220,  221,  222,

      223,  223,  223,  223,  224,  224,  225,  226,  227,  228,
      229,  230,  231,  232,  232,  232,  233,  234,  235,  236,
      236,  237,  238,  239,  240,  242,  243,  244,  245,  246,
      247,  248,  249,  250,  251,  252,  253,  254,  255,  257,
      258,  260,  262,  263,  264,  265,  266,  268,  269,  270,
      271,  272,  273,  274,  275,  276,  277,  278,  279,  280,
      280,  280,  281,  282,  283,  284,  285,  287,  288,  288,
      289,  289,  289,  290,  290,  290,  291,  292,  293,  294,
      295,  295,  296,  297,  298,  298,  299,  299,  300,  301,
      302,  303,  304,  306,  307,  308,  309,  310,  311,  312,

      313,  315,  317,  318,  319,  320,  321,  322,  324,  325,
      326,  327,  329,  330,  331,  332,  333,  335,  336,  337,
      338,  339,  341,  343,  344,  345,  346,  346,  346,  347,
      348,  348,  348,  348,  348,  349,  349,  349,  350,  352,
      354,  355,  356,  357,  358,  360,  361,  362,  363,  365,
      367,  368,  369,  370,  372,  373,  374,  375,  377,  379,
      380,  382,  383,  384,  386,  387,  389,  390,  390,  390,
      390,  390,  390,  390,  390,  390,  390,  390,  390,  390,
      392,  393,  394,  396,  398,  400,  402,  403,  404,  405,
      407,  408,  409,  410,  411,  413,  414,  416,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  419,  421,  422,
      424,  425,  427,  429,  431,  432,  434,  436,  436,  436,
      437,  438,  440,  441,  443,  445,  447,  449,  449
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   31,   31,   33,   34,
       35,   35,   35,   35,   35,   35,   35,   36,   37,   35,
       35,   38,   35,   39,   35,   35,   35,   40,   35,   35,
       41,   42,   43,   44,   45,    1,   46,   47,   48,   49,

       50,   51,   52,   53,   54,   35,   55,   56,   57,   58,
       59,   60,   35,   61,   62,   63,   64,   35,   65,   66,
       67,   35,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    2,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    5,    4,    4,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[347] =
    {   0,
        0,   64,   71,   79,    0,   81,    0,   82,  539,  540,
       85,  540,  540,  510,   70,    0,  509,  508,   67,  540,
      540,   69,  507,  540,   70,   82,   72,   98,  125,  506,
      540,   80,  505,   87,  504,    0,  115,  485,  471,   54,
      468,  540,  130,  540,  500,  482,   94,  129,   62,  476,
       84,  107,  469,  120,   85,  478,  464,  461,  475,  123,
      122,  459,  126,  465,  540,  490,  540,  540,  118,  112,
      175,   63,  181,  149,  540,  198,  540,  540,  206,  188,
      192,  540,  176,  509,  203,    0,  540,  540,  174,  504,
      218,  487,  540,  540,  540,  540,  201,  486,  540,  205,

      210,  225,    0,  235,  248,  540,  485,  540,  540,  540,
      484,  540,    0,  503,  498,  225,  453,  450,  443,  259,
      540,  540,  452,  456,  177,  458,  444,  241,  456,  443,
      222,  181,  452,  441,  439,  436,  437,  436,    0,  434,
      430,    0,  435,  429,  436,  216,    0,  427,  434,  424,
      430,  424,  417,  429,  419,  431,  540,  472,  467,  470,
      465,  268,  269,  540,  280,  540,  540,  284,  289,  540,
      468,  292,  540,  463,  294,  540,  540,  277,  280,    0,
      286,  290,  540,  540,  466,  465,  460,  459,  408,  419,
      418,  409,    0,  416,  407,  410,  407,  416,  399,  397,

        0,    0,  408,  408,  407,  410,  409,    0,  397,  406,
      393,    0,  404,  387,  391,  392,    0,  385,  384,  381,
      393,    0,    0,  387,  389,  385,  432,  427,  430,  425,
      428,  427,  422,  421,  540,  424,  419,  380,    0,    0,
      375,  367,  379,  363,    0,  370,  362,  369,    0,    0,
      362,  365,  357,    0,  373,  315,  326,    0,    0,  312,
        0,  320,  305,    0,  304,    0,  304,  341,  340,  332,
      331,  327,  321,  324,  319,  322,  321,  316,  315,    0,
      263,  262,    0,    0,    0,    0,  266,  260,  266,    0,
      265,  257,  272,  269,    0,  258,    0,    0,  307,  293,

      296,  282,  263,  255,  244,  238,  196,    0,  153,    0,
      147,    0,    0,    0,  157,    0,  540,  189,  162,  120,
      112,    0,   95,  540,    0,    0,    0,  540,  336,  341,
      346,  351,  353,  358,  363,  118,  368,  373,  378,  383,
      388,  393,  398,  403,  408,  413
    } ;

static const flex_int16_t yy_def[347] =
    {   0,
      328,    1,  329,  329,    1,    1,    1,    1,  328,  328,
      328,  328,  328,  328,  330,  331,  328,  328,  332,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  333,  333,  333,  333,  333,
      333,  328,  328,  328,  328,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  328,  328,  328,  328,  330,  332,
      333,  333,  333,  333,  328,  334,  328,  328,  334,  335,
      328,  328,  330,  328,  330,  331,  328,  328,  332,  328,
      332,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  336,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  333,  337,  338,  333,  333,  333,  333,  328,
      328,  328,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  328,  328,  328,  337,
      338,  333,  333,  328,  334,  328,  328,  335,  335,  328,
      339,  330,  328,  340,  332,  328,  328,  328,  328,  336,
      328,  328,  328,  328,  337,  328,  338,  328,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,

      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  341,  342,  328,  328,
      339,  339,  340,  340,  328,  343,  344,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  341,  341,  342,
      342,  345,  346,  339,  340,  343,  343,  344,  344,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  333,  333,  341,  342,

      345,  345,  346,  346,  343,  344,  333,  333,  333,  333,
      333,  333,  333,  333,  333,  333,  328,  345,  346,  333,
      333,  333,  333,  328,  333,  333,  333,    0,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328
    } ;

static const flex_int16_t yy_nxt[612] =
    {   0,
       10,   11,   12,   13,   10,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   36,   38,   36,   39,   36,   40,   41,   36,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   36,   54,   36,   55,   56,   57,   58,   59,
       60,   61,   62,   36,   63,   36,   64,   65,   66,   67,
       68,   69,   76,   77,   78,   70,   79,   84,   90,   80,
       76,   77,   78,   92,   79,  116,   81,   80,   69,   69,
       81,   98,   70,   70,  162,   71,   93,   95,   96,   99,

      116,   72,   97,   97,   97,   97,  107,  108,   91,  162,
       73,   85,   71,   71,  110,  111,  100,  129,   72,   72,
      130,  180,  114,  159,   74,  158,  115,   73,   73,  101,
      143,  120,  121,  121,  102,  120,  114,  103,  144,  132,
      115,   74,   74,  100,  101,  104,  104,  104,  104,  133,
      327,  124,  116,   91,  116,  125,  102,  105,  126,   85,
      134,  326,  135,  103,  325,  136,  116,  137,  149,  116,
      139,  151,  150,  324,  105,  116,  140,  141,  154,  155,
      162,  142,  160,  170,  152,  170,  161,  127,  160,  128,
      166,  166,  161,   81,  149,  162,  324,   81,  150,  165,

      166,  167,  323,  165,  172,  173,  168,  165,  166,  167,
      170,  165,  162,  322,  168,   91,  321,   85,  162,  175,
      173,   97,   97,   97,   97,   97,   97,   97,   97,  170,
      178,  178,  114,  105,  203,  162,  115,  105,  194,  127,
      320,  163,  204,  195,   85,  179,  179,  179,  114,  235,
      105,  235,  115,  100,  105,  104,  104,  104,  104,   91,
      120,  121,  121,  181,  120,  181,  319,  105,  182,  182,
      182,  182,  201,  216,  304,  160,  160,  202,  217,  161,
      161,  165,  166,  167,  105,  165,  166,  166,  168,  318,
      198,  166,  166,  172,  173,  175,  173,  178,  178,  170,

      179,  179,  179,  302,  317,  170,  182,  182,  182,  182,
      182,  182,  182,  182,  317,  316,  315,  314,  198,  313,
      312,  311,  310,  309,  308,  307,  306,  279,  305,  277,
      170,  170,  304,   85,  302,   91,   75,   75,   75,   75,
       75,   83,  300,  271,   83,   83,   86,  299,  269,   86,
       86,   89,  298,  297,   89,   89,  113,  113,  164,  164,
      164,  164,  164,  169,  169,  296,  169,  169,  185,  295,
      294,  185,  185,  187,  293,  292,  187,  187,  231,  231,
      231,  231,  231,  233,  233,  233,  233,  233,  268,  268,
      268,  268,  268,  270,  270,  270,  270,  270,  276,  276,

      276,  276,  276,  278,  278,  278,  278,  278,  301,  301,
      301,  301,  301,  303,  303,  303,  303,  303,  291,  290,
      289,  288,  287,  286,  285,  284,  283,  282,  281,  280,
      279,  277,  275,  234,  274,  232,  273,  272,  271,  269,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  235,  236,  235,  234,  232,  230,  229,  228,  227,
      226,  225,  224,  223,  222,  221,  220,  219,  218,  215,
      214,  213,  212,  211,  210,  209,  208,  207,  206,  205,

      200,  199,  197,  196,  193,  192,  191,  190,  189,  188,
      186,  184,  183,  177,  176,  174,  171,  157,  156,  153,
      148,  147,  146,  145,  138,  131,  123,  122,  119,  118,
      117,  112,  109,  106,   94,   88,   87,   82,  328,    9,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328
    } ;

static const flex_int16_t yy_chk[612] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    3,    3,    2,    3,   15,   19,    3,
        4,    4,    4,   22,    4,   40,   11,    4,    6,    8,
       11,   27,    6,    8,   72,    2,   22,   25,   25,   27,

       40,    2,   26,   26,   26,   26,   32,   32,   19,   72,
        2,   15,    6,    8,   34,   34,   28,   49,    6,    8,
       49,  336,   37,   70,    2,   69,   37,    6,    8,   28,
       55,   43,   43,   43,   28,   43,   48,   28,   55,   51,
       48,    6,    8,   29,   28,   29,   29,   29,   29,   51,
      323,   47,   37,   70,   60,   47,   28,   29,   47,   69,
       52,  321,   52,   28,  320,   52,   48,   52,   60,   60,
       54,   61,   60,  319,   29,   37,   54,   54,   63,   63,
       74,   54,   71,   83,   61,   89,   71,   48,   73,   48,
       80,   80,   73,   81,   74,   74,  318,   81,   74,   76,

       76,   76,  315,   76,   85,   85,   76,   79,   79,   79,
       85,   79,   71,  311,   79,   89,  309,   83,   73,   91,
       91,   97,   97,   97,   97,  100,  100,  100,  100,   91,
      101,  101,  116,   97,  132,   71,  116,  100,  125,   73,
      307,   73,  132,  125,   85,  102,  102,  102,  128,  306,
       97,  305,  128,  104,  100,  104,  104,  104,  104,   91,
      120,  120,  120,  105,  120,  105,  304,  104,  105,  105,
      105,  105,  131,  146,  303,  162,  163,  131,  146,  162,
      163,  165,  165,  165,  104,  165,  168,  168,  165,  302,
      128,  169,  169,  172,  172,  175,  175,  178,  178,  172,

      179,  179,  179,  301,  300,  175,  181,  181,  181,  181,
      182,  182,  182,  182,  299,  296,  294,  293,  163,  292,
      291,  289,  288,  287,  282,  281,  279,  278,  277,  276,
      275,  274,  273,  172,  272,  175,  329,  329,  329,  329,
      329,  330,  271,  270,  330,  330,  331,  269,  268,  331,
      331,  332,  267,  265,  332,  332,  333,  333,  334,  334,
      334,  334,  334,  335,  335,  263,  335,  335,  337,  262,
      260,  337,  337,  338,  257,  256,  338,  338,  339,  339,
      339,  339,  339,  340,  340,  340,  340,  340,  341,  341,
      341,  341,  341,  342,  342,  342,  342,  342,  343,  343,

      343,  343,  343,  344,  344,  344,  344,  344,  345,  345,
      345,  345,  345,  346,  346,  346,  346,  346,  255,  253,
      252,  251,  248,  247,  246,  244,  243,  242,  241,  238,
      237,  236,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  221,  220,  219,  218,  216,  215,  214,
      213,  211,  210,  209,  207,  206,  205,  204,  203,  200,
      199,  198,  197,  196,  195,  194,  192,  191,  190,  189,
      188,  187,  186,  185,  174,  171,  161,  160,  159,  158,
      156,  155,  154,  153,  152,  151,  150,  149,  148,  145,
      144,  143,  141,  140,  138,  137,  136,  135,  134,  133,

      130,  129,  127,  126,  124,  123,  119,  118,  117,  115,
      114,  111,  107,   98,   92,   90,   84,   66,   64,   62,
       59,   58,   57,   56,   53,   50,   46,   45,   41,   39,
       38,   35,   33,   30,   23,   18,   17,   14,    9,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,

      328,  328,  328,  328,  328,  328,  328,  328,  328,  328,
      328
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[106] =
    {   0,
0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include <bits/stdc++.h>
#include "parser.tab.h"
using namespace std;



#define MAX_DEPTH 100
#define YY_DECL int orig_yylex(void)
//indentation Stack
int indent_stack[MAX_DEPTH] ;
int level = 0 ;

int nesting = 0 ;
// stack for Braces
int nest_level = 0 ;
int enterLstart = 1 ;

// int last_newLine = 0 ;
// bool eof_flag = false ;

void NestingHandler(int a);
void process_indent(char* line); 
static void display_error(const char *msg);
void EndHandler() ;
int countt = 0;


/* The scanner state: based roughly on the code in the CPython tokeniser */
    int atbol;                  /* Nonzero if at begin of new line */
    int endbol;                 /* Nonzero if at end of EOF */
    int pendin;                 /* Pending indents (if > 0) or dedents (if < 0) */
    bool seen_endmarker;        /* Have we sent the ENDMARKER token yet? */

int NO_TOKEN = -1;
int pending_token = NO_TOKEN;          /* One token can be queued while processing indent/dedent */

int debug_mode = 0 ;

void debbugger1(string msg, int val) {
  // cout << "ENDMARKER IS : " << ENDMARKER << endl ;
  if(debug_mode)
    cout << "DEBUG: " << msg << val << endl ;
}
//Python Lexer
#line 825 "lex.yy.c"
/* We want to wrap the generated lexer with our own function */

/* without 00000 */

#line 830 "lex.yy.c"

#define INITIAL 0
#define LStart 1
#define File_End 2
#define DedentRelease 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 99 "lexer.l"

#line 101 "lexer.l"
              if(enterLstart) {
                BEGIN(LStart) ;
                enterLstart = 0 ;
              }

#line 1067 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 329 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 540 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];

find_rule: /* we branch to this label when backing up */

		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
					{
					(yy_full_match) = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 106 "lexer.l"
{
             yylval.intNumber = atoi(yytext);
             return LITERAL_INT;
           }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 110 "lexer.l"
{
             yylval.fltNumber = atof(yytext);
             return LITERAL_FLOAT;
           }
	YY_BREAK

case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 120 "lexer.l"
{
  //ignore blank lines
  //but it will end the logical line
  if (!nest_level && nesting){
    nesting = 0 ;
    return NEWLINE;
  }
}
	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 129 "lexer.l"
{
                // calculate first non space character
                process_indent(yytext) ;
                BEGIN(INITIAL) ;
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 135 "lexer.l"
{
      // calculate first non space character
      process_indent(yytext) ;
      BEGIN(INITIAL) ;
      REJECT;
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 142 "lexer.l"
/*fdfdfdfdfd*/ {
  // ignore to give the parser NEWLINE;
  // but turn on nesting
  debbugger1("Nesting", 0) ;
  nesting = 1 ;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 150 "lexer.l"
{
  // Handle Comments
  BEGIN(LStart) ;

}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 156 "lexer.l"
{
  //give the lexeme to the parser also handle byte strings
  yylval.sval = strdup(yytext) ;
  return BYTESTRING;
}
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 162 "lexer.l"
{
  //give the lexeme to the parser also handle byte strings
  yylval.sval = strdup(yytext) ;
  return STRING;
}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 168 "lexer.l"
{
  int last = yyleng - 1;
  while ((last >= 0) &&
        (yytext[last] != '\\')) {
    last-- ;
  }
  last--;

  // this may be incorrect
  while ((last >= 0)) {
    unput(yytext[last]);
    last-- ;
  }

  debbugger1("Multiline String Explicit Joined", 0) ;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 185 "lexer.l"
{ return KEY_FALS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 187 "lexer.l"
{ return KEY_NONE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 189 "lexer.l"
{ return KEY_TRU; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 191 "lexer.l"
{ return KEY_AS; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 193 "lexer.l"
{ return KEY_ASSERT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 195 "lexer.l"
{ return KEY_ASYNC; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 197 "lexer.l"
{ return KEY_AWAIT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 199 "lexer.l"
{ return KEY_BREAK; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 200 "lexer.l"
{ return KEY_CLASS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 201 "lexer.l"
{ return KEY_CONTINUE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 202 "lexer.l"
{ return KEY_DEF; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 203 "lexer.l"
{ return KEY_DEL; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 204 "lexer.l"
{ return KEY_ELIF; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 205 "lexer.l"
{ return KEY_ELSE; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 206 "lexer.l"
{ return KEY_EXCEPT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 207 "lexer.l"
{ return KEY_FINALLY; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 208 "lexer.l"
{ return KEY_FOR; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 209 "lexer.l"
{ return KEY_FROM; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 210 "lexer.l"
{ return KEY_GLOBAL; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 211 "lexer.l"
{ return KEY_IF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 212 "lexer.l"
{ return KEY_IMPORT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 213 "lexer.l"
{ return KEY_IN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 214 "lexer.l"
{ return KEY_IS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 215 "lexer.l"
{ return KEY_LAMBDA; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 216 "lexer.l"
{ return KEY_NONLOCAL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 217 "lexer.l"
{ return KEY_PASS; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 218 "lexer.l"
{ return KEY_RAISE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 219 "lexer.l"
{ return KEY_RETURN; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 220 "lexer.l"
{ return KEY_TRY; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 221 "lexer.l"
{ return KEY_WHILE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 222 "lexer.l"
{ return KEY_WITH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 223 "lexer.l"
{ return KEY_YIELD;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 225 "lexer.l"
{ return KEY_INT; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 227 "lexer.l"
{ return KEY_FLOAT; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 228 "lexer.l"
{ return KEY_STR; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 229 "lexer.l"
{ return KEY_BOOL; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 230 "lexer.l"
{ return KEY_LIST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 232 "lexer.l"
{ return OP_LOGICAL_AND; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 233 "lexer.l"
{ return OP_LOGICAL_NOT; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 234 "lexer.l"
{ return OP_LOGICAL_OR; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 235 "lexer.l"
{ return OP_PLUS; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 236 "lexer.l"
{ return OP_MINUS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 237 "lexer.l"
{ return OP_TIMES; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 238 "lexer.l"
{ return OP_DIVIDE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 239 "lexer.l"
{ return OP_FLOOR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 240 "lexer.l"
{ return OP_MOD; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 241 "lexer.l"
{ return OP_EXP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "lexer.l"
{ return OP_LSHIFT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 243 "lexer.l"
{ return OP_RSHIFT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 244 "lexer.l"
{ return OP_BITWISE_AND; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 245 "lexer.l"
{ return OP_BITWISE_OR; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 246 "lexer.l"
{ return OP_BITWISE_XOR; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 247 "lexer.l"
{ return OP_BITWISE_NOT; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 248 "lexer.l"
{ return OP_WALRUS;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 249 "lexer.l"
{ return OP_LESS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 250 "lexer.l"
{ return OP_GREATER; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 251 "lexer.l"
{ return OP_LESS_EQ; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 252 "lexer.l"
{ return OP_GREATER_EQ; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 253 "lexer.l"
{ return OP_EQ; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 254 "lexer.l"
{ return OP_NOT_EQ; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 257 "lexer.l"
{ NestingHandler(0) ;return DELIM_LPAR; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 258 "lexer.l"
{ NestingHandler(1) ;return DELIM_RPAR; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 259 "lexer.l"
{ NestingHandler(0) ;return DELIM_LBRACKET; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 260 "lexer.l"
{ NestingHandler(1) ;return DELIM_RBRACKET; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 261 "lexer.l"
{ NestingHandler(0) ;return DELIM_LBRACE; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 262 "lexer.l"
{ NestingHandler(1) ;return DELIM_RBRACE; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 264 "lexer.l"
{ return DELIM_COMMA; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 266 "lexer.l"
{ return DELIM_COLON; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 268 "lexer.l"
{ return DELIM_DOT; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 269 "lexer.l"
{ return DELIM_SEMICOLON; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 270 "lexer.l"
{ return DELIM_OP_AT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 271 "lexer.l"
{ return DELIM_ASSIGN; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 272 "lexer.l"
{ return DELIM_ARROW; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 273 "lexer.l"
{ return DELIM_PLUS_EQ; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 274 "lexer.l"
{ return DELIM_MINUS_EQ; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 275 "lexer.l"
{ return DELIM_TIMES_EQ; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 276 "lexer.l"
{ return DELIM_DIVIDE_EQ; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 277 "lexer.l"
{ return DELIM_FLOOR_EQ; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 278 "lexer.l"
{ return DELIM_MOD_EQ; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 279 "lexer.l"
{ return DELIM_MATMUL_EQ; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 280 "lexer.l"
{ return DELIM_AND_EQ; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 281 "lexer.l"
{ return DELIM_OR_EQ; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 282 "lexer.l"
{ return DELIM_XOR_EQ; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 283 "lexer.l"
{ return DELIM_RSHIFT_EQ; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 284 "lexer.l"
{ return DELIM_LSHIFT_EQ; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 285 "lexer.l"
{ return DELIM_EXP_EQ; }
	YY_BREAK
/*
      some reserved IDENTIFIERS
      */
case 97:
YY_RULE_SETUP
#line 291 "lexer.l"
{ yylval.sval = strdup(yytext); return RES_ID_SELF; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 292 "lexer.l"
{ yylval.sval = strdup(yytext); return RES_ID_INIT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 293 "lexer.l"
{ yylval.sval = strdup(yytext); return RES_ID_MAIN; }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 299 "lexer.l"
{
  /* for newline */
  // debbugger("TOKEN: Newline", 0) ;
  if (!nest_level){
    BEGIN(LStart) ;
    return NEWLINE;
  }
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 309 "lexer.l"
{
  // Handle Comments
  debbugger1("Comment", 0) ;
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LStart):
case YY_STATE_EOF(File_End):
case YY_STATE_EOF(DedentRelease):
#line 315 "lexer.l"
{
  if (nest_level) {
    display_error("Unmatched Braces") ;
  }

  EndHandler() ;
  return ENDMARKER;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 325 "lexer.l"
{ 
  /* for IDENTIFIERS */
  yylval.sval = strdup(yytext) ;
  return IDENTIFIER;  
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 332 "lexer.l"
{
  // cout << "DEBUG: Space" << endl ;
  // ignore whitespaces
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 337 "lexer.l"
{
  // Handle Error
  display_error("Invalid Character") ;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 342 "lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1768 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 329 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 329 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 328);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 342 "lexer.l"


void EndHandler() {
  endbol = 1;
}

static void display_error(const char *msg)
{
    /* fprintf (stderr, "%d.%d-%d.%d:", yylloc.first_line, yylloc.first_column,
                                     yylloc.last_line,  yylloc.last_column); */
    fprintf(stderr, "Error:%d lexical error with [%s]: %s\n", yylineno, yytext, msg);
    /* line ki facility dalni hai  */
    exit(EXIT_FAILURE);
    /* dont know what it is */
}



void NestingHandler(int a) {
  if (a == 0) {
    /* turn on nesting */
    nesting = 1 ;
    ++nest_level ;
  } else {
    if (nest_level) {
      --nest_level ;

    if(nest_level == 0)
      nesting = 0 ;
    }
    else {
      display_error("Unmatched Braces") ;
    }
  }

}
string TOKENString(int token) {
  switch (token) {
    case NEWLINE: return "NEWLINE" ;
    case INDENT: return "INDENT" ;
    case DEDENT: return "DEDENT" ;
    case LITERAL_INT: return "LITERAL_INT" ;
    case LITERAL_FLOAT: return "LITERAL_FLOAT" ;
    case STRING: return "STRING" ;
    case IDENTIFIER: return "IDENTIFIER" ;

    case OP_BITWISE_AND: return "OP_BITWISE_AND" ;
    case OP_BITWISE_NOT: return "OP_BITWISE_NOT" ;
    case OP_BITWISE_OR: return "OP_BITWISE_OR" ;
    case OP_BITWISE_XOR: return "OP_BITWISE_XOR" ;
    case OP_DIVIDE: return "OP_DIVIDE" ;
    case OP_EQ: return "OP_EQ" ;
    case OP_TIMES: return "OP_TIMES" ;
    case OP_EXP: return "OP_EXP" ;
    case OP_GREATER: return "OP_GREATER" ;
    case OP_GREATER_EQ: return "OP_GREATER_EQ" ;
    case OP_LSHIFT: return "OP_LSHIFT" ;
    case OP_LESS: return "OP_LESS" ;
    case OP_LESS_EQ: return "OP_LESS_EQ" ;
    case OP_LOGICAL_AND: return "OP_LOGICAL_AND" ;
    case OP_LOGICAL_NOT: return "OP_LOGICAL_NOT" ;

    case DELIM_AND_EQ: return "DELIM_AND_EQ" ;
    case DELIM_ARROW: return "DELIM_ARROW" ;
    case DELIM_ASSIGN: return "DELIM_ASSIGN" ;
    case DELIM_COLON: return "DELIM_COLON" ;
    case DELIM_COMMA: return "DELIM_COMMA" ;
    case DELIM_DOT: return "DELIM_DOT" ;
    case DELIM_FLOOR_EQ: return "DELIM_FLOOR_EQ" ;
    case DELIM_LBRACE: return "DELIM_LBRACE" ;
    case DELIM_LBRACKET: return "DELIM_LBRACKET" ;
    case DELIM_LPAR: return "DELIM_LPAR" ;
    case DELIM_MINUS_EQ: return "DELIM_MINUS_EQ" ;
    case DELIM_MOD_EQ: return "DELIM_MOD_EQ" ;
    case DELIM_OR_EQ: return "DELIM_OR_EQ" ;
    case DELIM_PLUS_EQ: return "DELIM_PLUS_EQ" ;
    case DELIM_RBRACE: return "DELIM_RBRACE" ;
    case DELIM_RBRACKET: return "DELIM_RBRACKET" ;
    case DELIM_RPAR: return "DELIM_RPAR" ;
    case DELIM_SEMICOLON: return "DELIM_SEMICOLON" ;
    case DELIM_TIMES_EQ: return "DELIM_TIMES_EQ" ;
    case DELIM_XOR_EQ: return "DELIM_XOR_EQ" ;
    case DELIM_EXP_EQ: return "DELIM_EXP_EQ" ;
    case DELIM_MATMUL_EQ: return "DELIM_MATMUL_EQ" ;
    case DELIM_RSHIFT_EQ: return "DELIM_RSHIFT_EQ" ;
    case DELIM_LSHIFT_EQ: return "DELIM_LSHIFT_EQ" ;
    case DELIM_OP_AT: return "DELIM_OP_AT" ;

    case KEY_YIELD: return "KEY_YIELD" ;
    case KEY_WITH: return "KEY_WITH" ;
    case KEY_WHILE: return "KEY_WHILE" ;
    case KEY_TRY: return "KEY_TRY" ;
    case KEY_RETURN : return "KEY_RETURN" ;
    case KEY_BOOL: return "KEY_BOOL" ;
    case KEY_STR: return "KEY_STR" ;
    case KEY_FLOAT: return "KEY_FLOAT" ;
    case KEY_INT: return "KEY_INT" ;
    case KEY_LIST: return "KEY_LIST" ;
    case KEY_FALS: return "KEY_FALS" ;
    case KEY_TRU: return "KEY_TRU" ;
    case KEY_BREAK: return "KEY_BREAK" ;
    case KEY_AS: return "KEY_AS" ;
    case KEY_ASSERT: return "KEY_ASSERT" ;
    case KEY_ASYNC: return "KEY_ASYNC" ;
    case KEY_AWAIT: return "KEY_AWAIT" ;
    case KEY_CLASS: return "KEY_CLASS" ;
    case KEY_CONTINUE: return "KEY_CONTINUE" ;
    case KEY_DEF: return "KEY_DEF" ;
    case KEY_DEL: return "KEY_DEL" ;
    case KEY_ELIF: return "KEY_ELIF" ;
    case KEY_ELSE: return "KEY_ELSE" ;
    case KEY_EXCEPT: return "KEY_EXCEPT" ;
    case KEY_FINALLY: return "KEY_FINALLY" ;
    case KEY_FOR: return "KEY_FOR" ;
    case KEY_FROM: return "KEY_FROM" ;
    case KEY_GLOBAL: return "KEY_GLOBAL" ;
    case KEY_IF: return "KEY_IF" ;
    case KEY_IMPORT: return "KEY_IMPORT" ;
    case KEY_IN: return "KEY_IN" ;
    case KEY_IS: return "KEY_IS" ;
    case KEY_LAMBDA: return "KEY_LAMBDA" ;
    case KEY_NONE: return "KEY_NONE" ;
    case KEY_NONLOCAL: return "KEY_NONLOCAL" ;
    case KEY_PASS: return "KEY_PASS" ;
    case KEY_RAISE: return "KEY_RAISE" ;

    case ENDMARKER: return "ENDMARKER" ;
    default: return "TOKEN" ;
  }
}
 int yylex(void)
{
    int token = NO_TOKEN;
    if (seen_endmarker){
      yyterminate();
    }
    //First check for any pending indents or dedents 
    if (pendin < 0) {
        pendin ++;
        token = DEDENT;
    }
    else if (pendin > 0) {
        pendin --;
        token = INDENT;
    }
    // Next check for a pending token 
    else if (pending_token != NO_TOKEN) {
        token = pending_token;
        pending_token = NO_TOKEN;
    }
    // Finally, call the actual scanner 
    else {
        token = orig_yylex();
        if (token == NEWLINE) {
            atbol = true;
        }
        else if (atbol || endbol) {
            if(token == ENDMARKER)
            {
              /* make a empty char* */
              char* line = NULL;
              yyleng = 0;
              process_indent(line);
              pending_token = token;
              if(atbol) token = yylex();
              else token = NEWLINE;
            }
            else{
              pending_token = token;
              token = yylex();
            }
          atbol = false;
            
        }
        //if we get here then nothing is pending, so just return the token 
    }
    if (token == ENDMARKER){
      seen_endmarker = true;  //Wrap up the next time around 
    }
    debbugger1("TOKEN: " + TOKENString(token) + " " + to_string(token) + " ", countt++) ;
    return token;
}

unsigned int white_count(char* line) {
  unsigned int count = 0 ;
  int maxl = yyleng ;
  for (int i = 0; i < maxl; i++) {
    if (line[i] == ' ') {
      count++ ;
    } else {
      break ;
    }
  }
  return count ;
}

void process_indent(char* line) {

  if (nesting)
    /* Ignore indents while nested. */
    return;

  unsigned int indent = white_count(line) ;

  if (indent == indent_stack[level]) {
    /* do nothing if equal */
  }

  if (indent > indent_stack[level]) {
    assert(level+1 < MAX_DEPTH) ;
    pendin++;
    indent_stack[++level] = indent ;
  }

  while (indent < indent_stack[level]) {
    --level ;
    pendin--;
    /* correct it  */
  }

  if(indent != indent_stack[level])
  {
    /* Handle error */
  }

  assert(level >= 0) ;
}

